/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'profileCompletionPercentage' : bigint,
  'matchCount' : bigint,
}
export interface Profile {
  'desiredPostingLocation' : string,
  'userId' : Principal,
  'designation' : string,
  'createdAt' : Time,
  'division' : string,
  'fullName' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
  'department' : string,
  'railwayZone' : string,
  'currentPostingLocation' : string,
  'contactVisible' : boolean,
}
export interface PublicUser {
  'name' : string,
  'division' : string,
  'email' : [] | [string],
  'location' : string,
  'railwayZone' : string,
}
export interface SearchFilters {
  'designation' : [] | [string],
  'zone' : [] | [string],
  'division' : [] | [string],
  'location' : [] | [string],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUsers' : ActorMethod<[], Array<PublicUser>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMatches' : ActorMethod<[], Array<Profile>>,
  'getMyProfile' : ActorMethod<[], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerOrLogin' : ActorMethod<[], Profile>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'searchProfiles' : ActorMethod<[SearchFilters], Array<Profile>>,
  'updateProfile' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];