/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublicUser = IDL.Record({
  'name' : IDL.Text,
  'division' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'railwayZone' : IDL.Text,
});
export const Time = IDL.Int;
export const Profile = IDL.Record({
  'desiredPostingLocation' : IDL.Text,
  'userId' : IDL.Principal,
  'designation' : IDL.Text,
  'createdAt' : Time,
  'division' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'department' : IDL.Text,
  'railwayZone' : IDL.Text,
  'currentPostingLocation' : IDL.Text,
  'contactVisible' : IDL.Bool,
});
export const DashboardStats = IDL.Record({
  'profileCompletionPercentage' : IDL.Nat,
  'matchCount' : IDL.Nat,
});
export const SearchFilters = IDL.Record({
  'designation' : IDL.Opt(IDL.Text),
  'zone' : IDL.Opt(IDL.Text),
  'division' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(PublicUser)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getMyProfile' : IDL.Func([], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerOrLogin' : IDL.Func([], [Profile], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'searchProfiles' : IDL.Func([SearchFilters], [IDL.Vec(Profile)], ['query']),
  'updateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublicUser = IDL.Record({
    'name' : IDL.Text,
    'division' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'railwayZone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Profile = IDL.Record({
    'desiredPostingLocation' : IDL.Text,
    'userId' : IDL.Principal,
    'designation' : IDL.Text,
    'createdAt' : Time,
    'division' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'department' : IDL.Text,
    'railwayZone' : IDL.Text,
    'currentPostingLocation' : IDL.Text,
    'contactVisible' : IDL.Bool,
  });
  const DashboardStats = IDL.Record({
    'profileCompletionPercentage' : IDL.Nat,
    'matchCount' : IDL.Nat,
  });
  const SearchFilters = IDL.Record({
    'designation' : IDL.Opt(IDL.Text),
    'zone' : IDL.Opt(IDL.Text),
    'division' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(PublicUser)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getMyProfile' : IDL.Func([], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerOrLogin' : IDL.Func([], [Profile], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'searchProfiles' : IDL.Func([SearchFilters], [IDL.Vec(Profile)], ['query']),
    'updateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };